dist: xenial
language: elixir
install: true
sudo: true
before_install:
 - sudo apt-get update && sudo apt-get install postgresql-client
 - docker run --detach --rm --hostname postgres --name postgres -e POSTGRES_PASSWORD=postgres -p 5432 postgres:9.6.10-alpine
 - export POSTGRES_PORT=$(docker inspect --format '{{ (index (index .NetworkSettings.Ports "5432/tcp") 0).HostPort }}' postgres )
 - until PGPASSWORD=postgres psql -h localhost -U "postgres" -p $POSTGRES_PORT -c '\q' &> /dev/null ; do printf '.'; sleep 1; done
elixir:
  - '1.8'
before_script:
  - "mix local.hex --force"
  - "mix local.rebar --force"
  - "mix deps.get"
script:
  - "mix test"
after_success:
  - MIX_ENV=test mix coveralls.travis
otp_release:
  - '21.0.9'
cache:
  directories:
    - _build
    - deps
services:
  - docker
